name: project_la
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  dio: ^5.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  location: ^4.4.0
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
