// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx6fZFn7zBDKJScWqCL9MJSIIK0uviePw',
    appId: '1:41032947784:web:13c8bf3282a0ce2d37e07d',
    messagingSenderId: '41032947784',
    projectId: 'login-e68e7',
    authDomain: 'login-e68e7.firebaseapp.com',
    storageBucket: 'login-e68e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJEdycTwd_XfUEYk5TkWFy_bGszZkKrMc',
    appId: '1:41032947784:android:714d9f42c8cfb1c437e07d',
    messagingSenderId: '41032947784',
    projectId: 'login-e68e7',
    storageBucket: 'login-e68e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepARePTqAAChe6VS1cgrU-Xm2I6gFQWU',
    appId: '1:41032947784:ios:2385b122c84d5e8c37e07d',
    messagingSenderId: '41032947784',
    projectId: 'login-e68e7',
    storageBucket: 'login-e68e7.appspot.com',
    iosClientId: '41032947784-m14sisckf2qfh15j111390i7ncdtkebb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBepARePTqAAChe6VS1cgrU-Xm2I6gFQWU',
    appId: '1:41032947784:ios:2385b122c84d5e8c37e07d',
    messagingSenderId: '41032947784',
    projectId: 'login-e68e7',
    storageBucket: 'login-e68e7.appspot.com',
    iosClientId: '41032947784-m14sisckf2qfh15j111390i7ncdtkebb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectLa',
  );
}
